name: build-static
on: 
  push:
    branches: [main]
  
jobs:
  run-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install .
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
        path: ./www/dist

